### ISSUE TITLE
Update Gateway's nRF and ESP board files

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.boards.c#19]
Seems that the board files are made for the old A1 PCB revision. Let's update them to match the latest A2 revision:

https://github.com/ruuvi/gateway_hw

**Comment by TheSomeMan** [comment]
It turned out that this task had already been done in commit 184e8cf7ac55f11042884823e65645baa6abb617
[ruuvi.gateway_nrf.c](https://github.com/ruuvi/ruuvi.gateway_nrf.c) repo uses the obsolete version of ruuvi.boards.c.

**Comment by laurijamsa** [comment]
I didn't review the commit https://github.com/ruuvi/ruuvi.boards.c/commit/184e8cf7ac55f11042884823e65645baa6abb617 but I checked that the nRF firmware master branch is referring to the latest board file. Moving to done.
